### ISSUE TITLE
bitergia/elasticsearch:6.8.6-secured image contains propietary software

### ISSUE THREAD

**Issue by canasdiaz** [Bitergia/elasticsearch#4]
According to the Elasticsearch release notes since 6.3 it is not needed to enable X-Pack, it is distributed by default. This means the `6.8.6-secured` Docker image is distributing proprietary software due to the following line:

https://github.com/Bitergia/elasticsearch/blob/23b0c128c1a5107c693c7c0d4c8ab27536ef6113/docker/Dockerfile#L15

More info at https://www.elastic.co/guide/en/elasticsearch/reference/6.8/release-highlights-6.3.0.html

In order to get the libre software version it is needed to follow these instructions https://www.elastic.co/guide/en/elasticsearch/reference/6.8/deb.html#install-deb, where we can read: "Alternatively, you can download the following package, which contains only features that are available under the Apache 2.0 license: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.8.6.deb"

**Comment by sduenas** [comment]
Is there any tar.gz file we can use? It would be better to have a `tar.gz` so we don't have to change all the release process in the Dockerfile.

My apologies for generating this problem. I should have checked better these notes. I was only focused on the problems with mappings and compatibility that I didn't pay enough attention to this issue. I thought problems were only in 7.x and not starting in 6.3.

Anyway, no customers are using this and the image contains free software.

**Comment by canasdiaz** [comment]
> Is there any tar.gz file we can use? It would be better to have a `tar.gz` so we don't have to change all the release process in the Dockerfile.
> 
> My apologies for generating this problem. I should have checked better these notes. I was only focused on the problems with mappings and compatibility that I didn't pay enough attention to this issue. I thought problems were only in 7.x and not starting in 6.3.
> 
> Anyway, no customers are using this and the image contains free software.

Well, you know, shit happens. In any case I confirm you are right about the impact @sduenas . We are just using this for testing purposes. 

I'll look for the tar.gz file.

**Comment by canasdiaz** [comment]
I've just tried with `https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.8.6.tar.gz` and it works. In any case this is something we have to review carefully so let's look for more information in the downloads section.

**Comment by canasdiaz** [comment]
As soon as the new Docker image is created, we can close this ticket @sduenas

**Comment by canasdiaz** [comment]
I guess the image is created and we can close this ticket. Can u confirm @dlumbrer @sduenas ?

**Comment by sduenas** [comment]
Yes. It should have been closed before but GitHub doesn't close tickets automatically when they are in other branches. There's a reference to close this ticket in the commit.
