### ISSUE TITLE
VOLUME definition is wrong

### ISSUE THREAD

**Issue by yankcrime** [Bitergia/elasticsearch#5]
The [original version](https://github.com/dockerfile/elasticsearch/blob/master/Dockerfile) of this Docker image build definition specifies a `VOLUME` and `WORKDIR` of `/data`.  However, it does this in conjunction with a [configuration file](https://github.com/dockerfile/elasticsearch/blob/master/config/elasticsearch.yml) which ensures that ES makes use of that volume.

In the case of this version no such configuration file is used, which means that the default `/elasticsearch/data` is used to store ES data.

This can catch users out if they're expecting their ES data to be persistent.

Furthermore, depending on how users make use of a persistent Docker volume for their data, permissions can be a problem if they decide to bind mount a folder from the host into their container, owing to the requirement to run as an unprivileged user.  The startup script needs to be amended to `chown` the target directory when a container is started.

**Comment by yankcrime** [comment]
I've got fixes for the above but not sure how the maintainers of this repo would like to proceed.  The original version upstream doesn't appear to be maintained any more, so it doesn't make sense pushing fixes there.

**Comment by sduenas** [comment]
Hi @yankcrime,

would you mind to send a PR with those changes?

**Comment by sduenas** [comment]
Fixed by #8
